resources:
- ../base

nameSuffix: -dev
namespace: hms-dev

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: hms-pos-depl
    path: patch-env.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: hms-pos-depl
    path: patch-service-account.yaml