apiVersion: v1
kind: Service
metadata:
  name: hms-pos-svc
spec:
  selector:
    app: hms-pos-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hms-pos-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hms-pos-pod
  template:
    metadata:
      labels:
        app: hms-pos-pod
    spec:
      serviceAccountName: hms-pods-sa
      containers:
        - name: hms-pos-app
          image: somnathbm/hms-pos-svc:v0.0.12
          ports:
          - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /pos/healthy
              port: 8000
            periodSeconds: 20
            initialDelaySeconds: 10